#
# prezto - mimic the default prezto prompt (sorin)
#

add_newline = false

# A minimal left prompt
format = """
$username$nodejs$git_state$git_status$fill\
$directory\
$python\
$jobs$time
$character
"""

# move the rest of the prompt to the right
right_format = """$status$git_branch$git_status"""

[character]
success_symbol = "[â¯](red)[â¯](yellow)[â¯](green)"
error_symbol = "[â¯](red)[â¯](red)[â¯](red)"
vicmd_symbol = "[â®](green)[â®](yellow)[â®](red)"

[git_branch]
format = '[$branch]($style) '
style = 'bold green'

[python]
format = '[(\($virtualenv\) )]($style)'
style = 'white'

[git_status]
format = '$all_status$ahead_behind '
ahead = '[â¬†](bold purple) '
behind = '[â¬‡](bold purple) '
staged = '[âœš](green) '
deleted = '[-](red) '
renamed = '[âœ](purple) '
stashed = '[âœ­](cyan) '
untracked = '[??](white) '
modified = '[Î”](blue) '
conflicted = '[â•](yellow) '
diverged = 'â‡•'
up_to_date = '[](black)'

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"


[directory]
format = "[ $path ]($style)"
style = "purple"
read_only = "ï ½"
truncation_length = 3
truncate_to_repo = false
fish_style_pwd_dir_length = 1

[directory.substitutions]
"Documents" = "ó°ˆ™"
"Downloads" = "ï€™"
"Music" = "ï€"
"Pictures" = "ï€¾"
".config" = "Î£"
"Config" = "Î£"
"Workspace" = "ğŸ–¥"
"Games" = "ğŸ®ï¸"
#"Videos" = ""
"Media" = "â‰¡"
"bin" = "Î²"
"Local" = "Î›"
".local" = "Î›"
"Backup" = "â†º"

[cmd_duration]
format = '[$duration]($style) '

[line_break]
disabled = true

[status]
disabled = false
symbol = 'âœ˜ '

[fill]
symbol = "Â·"

[palettes.custom]
pastel_purple = "#9d64a3"
soft_lavender = "#E0D6FF"   


[hostname]
ssh_only = true
format = "[$hostname]($style)[â¯](green)"
style = "blue"
disabled = false

[username]
disabled = false
format = "[$user]($style)"
style_user = "yellow"
