[settings]
default_interval = 150
disable_media_keys = false  # Set to true to let system handle media keys (GNOME/KDE/etc.)
#shell = "/bin/bash"  # Override $SHELL
env_file = "~/.profile"
#notify_on_overlay_change = false  # Set to true for desktop notifications on overlay changes  

[shortcuts]
"super+k" = "edit_config"
"ctrl+shift+k" = "kill_switch"

#"ctrl+shift+a.repeat-toggle(10)" = "ydotool click 0xC0"

#-[LAUNCHERS]--------------------------------

"super.onrelease" = "hotline"
"super.doubletap" = "$LAUNCHER"

"super+enter" = "kitty"
"super+b" = "$BROWSER"
"super+shift+b" = "brave"
"super+e" = "thunderbird"
"super+w" = "whatsapp"
"super+f" = "$FILEMANAGER"
"super+v" = "copyq toggle"
"shift+super+n" = "notetaker"

#-[WINDOW MANAGER]---------------------------

# "super+q" = "close_window"
"super+x" = "kill_window"

#"super+1" = "workspace1"
#"super+2" = "workspace2"
#"super+3" = "workspace3"
#"super+4" = "workspace4"

#-[UTILS]------------------------------------

"print" = "grimblast -f copy area"
"print.doubletap" = "notify-send amogus"
"super+p" = "grimblast copy area"
"super+shift+p" = "grimblast copy"
"shift+print" = "grimblast copy"
"super+h" = "yap toggle"

"ctrl+print" = "bash -c \"xdg-open ~/Media/Pictures/temp.png\""
"f9" = "yap"
"102nd" = "notify-send penis"
"ctrl+shift+alt+h" = "xdotool mousemove_relative 2 0"



#-[MEDIA KEYS]-------------------------------

# Uncomment the keys you want to use
# Dependencies:
#   - pactl (audio control via PulseAudio/PipeWire)
#   - brightnessctl (brightness control)
#   - playerctl (optional, for media playback control)

#"volumeup" = "volume_up"
"volumeup.repeat-whileheld(100)" = "volume_up"
#"volumedown" = "volume_down"
"volumedown.repeat-whileheld(100)" = "volume_down"
"mute" = "mute_toggle"
"brightnessup" = "brightness_up"
"brightnessdown" = "brightness_down"
"playpause" = "media_play_pause"
"nextsong" = "media_next"
"previoussong" = "media_previous"

"ctrl+mute" = "mute_mic"
"ctrl+volumeup" = "mic_up"
"ctrl+volumedown" = "mic_down"

"ctl+brightnessup" = "hyprctl hyprsunset temperature +200"
"ctl+brightnessdown" = "hyprctl hyprsunset temperature -200"

#"shift+brightnessup" = "brightness_up"

[command_variables]#--------------------------

edit_config = "kitty micro ~/.config/akeyshually/config.toml"
kill_switch = "akeyshually stop && pkill -9 akeyshually"

#-[LAUNCHERS]--------------------------------

rofi = "~/.config/rofi/scripts/launcher_t7"
thunderbird = "thunderbird"
whatsapp = "flatpak run com.rtosta.zapzap"
browser2 = "brave-browser --user-data-dir=/home/user/.config/BraveSoftware/2"
notetaker = "bash -c \"source ~/.bashrc && /home/user/.config/bash/bin/notetaker/notetaker\""

#-[UTILS]------------------------------------

prtscr = "/home/user/Workspace/tools/bin/screenshot-save --temp"
yap = "notify-send 'yap'"
mute_mic = "pactl set-source-mute @DEFAULT_SOURCE@ toggle || wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"


#-[MEDIA COMMANDS]---------------------------

volume_up = "wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"
volume_down = "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
mute_toggle = "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
brightness_up = "~/.config/hypr/scripts/sunset +5"
brightness_down = "~/.config/hypr/scripts/sunset -5"
media_play_pause = "playerctl play-pause"
media_next = "playerctl next"
media_previous = "playerctl previous"

mic_up = "pactl set-source-volume @DEFAULT_SOURCE@ +10%   || wpctl set-volume @DEFAULT_AUDIO_SOURCE@ 5%+"
mic_down = "pactl set-source-volume @DEFAULT_SOURCE@ -10%   || wpctl set-volume @DEFAULT_AUDIO_SOURCE@ 5%-"
