
[settings]
default_loop_interval = 0.0017
disable_media_keys = false
#shell = "/bin/bash"  # Override $SHELL
env_file = "~/.profile" # source before commands

[shortcuts]
"super+k" = "edit_config"
"super+ctrl+k" = "swap"

#-[LAUNCHERS]--------------------------------

"super.onrelease" = "rofi"
"super+b" = "browser"
"super+shift+b" = "browser2"
"super+return" = "kitty"
"super+f" = "dolphin"
"super+x" = "xkill"
"super+e" = "email"
#"ctrl+alt+t" = "kitty"
"super+v" = "copyq toggle"
"super+w" = "whatsapp"
"shift+super+n" = "notetaker"

#-[UTILS]------------------------------------

"print" = "/home/luar/Workspace/tools/bin/screenshot-save --temp"
"super+p" = "/home/luar/Workspace/tools/bin/screenshot-save --temp"
"shift+print" = "/home/luar/Workspace/tools/bin/screenshot-save"
"ctrl+print" = "bash -c \"xdg-open ~/Media/Pictures/temp.png\""
"f9" = "yap"
"ctrl+mute" = "mute_mic"


"ro" = "notify-send 'Akeyshually 1' && dots akeyshually 1 && dots kanata vimsanity && pkexec systemctl daemon-reload  && pkexec systemctl restart kanata.service"
"super+t" = "date +%s.%N > /tmp/keypress-time"




"k.whileheld" = "xdotool mousemove_relative -- 0 -2"
"j.whileheld" = "xdotool mousemove_relative -- 0 2"
"h.whileheld" = "xdotool mousemove_relative -- -2 0"
"l.whileheld" = "xdotool  mousemove_relative -- 2 0"
"ctrl+k" = "xdotool key --clearmodifiers k"
"ctrl+j" = "xdotool key --clearmodifiers j"
"ctrl+h" = "xdotool key --clearmodifiers h"
"ctrl+l" = "xdotool key --clearmodifiers l"



#-[MEDIA KEYS]-------------------------------

# "volumeup" = "volume_up"
# "volumedown" = "volume_down"
# "mute" = "mute_toggle"
# "brightnessup" = "brightness_up"
# "brightnessdown" = "brightness_down"
# "playpause" = "media_play_pause"
# "nextsong" = "media_next"
# "previoussong" = "media_previous"

[command_variables]#--------------------------

edit_config = "kitty micro ~/.config/akeyshually/config.toml"
swap = "dots akeyshually 1"

browser = "brave-browser --user-data-dir=/home/luar/.config/BraveSoftware/luar"
browser2 = "brave-browser --user-data-dir=/home/luar/.config/BraveSoftware/dan"
dmenu = "bash -c \"compgen -c | dmenu | sh\""
rofi = "~/.config/rofi/scripts/launcher_t7"
searchapp = "dbus-send --session --dest=org.gnome.Shell --type=method_call /org/gnome/Shell org.freedesktop.DBus.Properties.Set string:org.gnome.Shell string:OverviewActive variant:boolean:true"
email = "flatpak run org.mozilla.Thunderbird"
yap = "yap toggle"
mute_mic = "pactl set-source-mute @DEFAULT_SOURCE@ toggle"
whatsapp = "flatpak run com.rtosta.zapzap"
notetaker = "bash -c \"source ~/.bashrc && /home/luar/.config/bash/bin/notetaker/notetaker\""

# Media key commands (uncomment shortcuts above to use)
volume_up = "pactl set-sink-volume @DEFAULT_SINK@ +5%"
volume_down = "pactl set-sink-volume @DEFAULT_SINK@ -5%"
mute_toggle = "pactl set-sink-mute @DEFAULT_SINK@ toggle"
brightness_up = "brightnessctl set +5%"
brightness_down = "brightnessctl set 5%-"
media_play_pause = "playerctl play-pause"
media_next = "playerctl next"
media_previous = "playerctl previous"
